version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.9
    working_directory: ~/repo

    steps:
      - checkout

      - run: ls -l node_modules/@laser-dac
      - run: yarn install
      - run: yarn test
